site_name: Роза Тихонова, портфолио
docs_dir: source
site_dir: docs

theme:
  name: material
  language: ru

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лаб. работа 1: labs/lab1.md
      - Лаб. работа 2: labs/lab2.md
      - Лаб. работа 3: labs/lab3.md
      - Лаб. работа 4: labs/lab4.md
      - Лаб. работа 5: labs/lab5.md
      
extra:
  generator: false